services:
  laravel-app:
    build: .
    image: laravel-app:latest
    container_name: laravel-app
    restart: always
    ports:
      - "9001:9000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    command: sh -c "while ! nc -z mysql 3306; do sleep 1; done; php-fpm"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
